[[main]]
name = "首页"
pageRef = "/"
weight = 10

[[main]]
name = "Solidity教程"
pageRef = "/docs/solidity"
weight = 20
identifier = "solidity"

[[main]]
name = "Dex教程"
pageRef = "/docs/dex"
weight = 40
identifier = "dex"

[[main]]
name = "区块链技术"
pageRef = "/docs/blockchain"
weight = 50
identifier = "blockchain"

[[main]]
name = "工具"
pageRef = "/docs/more"
weight = 60
identifier = "more"



